I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 41, in script
    show mc_normal at move_left_to_right(0.1,0.4)
  File "game/script.rpy", line 41, in <module>
    show mc_normal at move_left_to_right(0.1,0.4)
Exception: Too many arguments passed to ATL transform.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 41, in script
    show mc_normal at move_left_to_right(0.1,0.4)
  File "D:\mauri1\renpy-8.2.3-sdk\renpy\ast.py", line 1113, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "D:\mauri1\renpy-8.2.3-sdk\renpy\ast.py", line 1072, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "D:\mauri1\renpy-8.2.3-sdk\renpy\ast.py", line 1072, in <listcomp>
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "D:\mauri1\renpy-8.2.3-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\mauri1\renpy-8.2.3-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 41, in <module>
    show mc_normal at move_left_to_right(0.1,0.4)
  File "D:\mauri1\renpy-8.2.3-sdk\renpy\atl.py", line 601, in __call__
    raise Exception("Too many arguments passed to ATL transform.")
Exception: Too many arguments passed to ATL transform.

Windows-10-10.0.19041 AMD64
Ren'Py 8.2.3.24061702
Irreal 1.0
Sun Nov 17 13:09:30 2024
